### ISSUE TITLE
Sankey-path is not visible with gardient

### ISSUE THREAD

**Issue by ch-bas** [uniberg/kbn_sankey_vis#13]
**Description :** 
This issue was reported by @bfgiordano.
After adding gradient for the link path between nodes, for some reasons, it was not rendered correctly.

![96130628-2f037000-0ec6-11eb-8336-b76766825319](https://user-images.githubusercontent.com/18037647/97455872-998dc480-1938-11eb-8770-b9321a2a74d1.png)

In order to see the correct path, you had to drag-and-drop one of the nodes( source or target).
This misbehaving can be related to this issue in the official 'd3-sankey' [repository](https://github.com/d3/d3-sankey/issues/28).

**Expected Behaviour:**

All the links between the nodes should **be visible** properly.

**Comment by bfgiordano** [comment]
Thank you for opening issue -- I had not had a chance to get to it.

**Comment by ch-bas** [comment]
Closed via #16

**Comment by bfgiordano** [comment]
Thank you for working in tis --- I look forward to installing and
experimenting!
Barbara
