### ISSUE TITLE
Sankey update for 7.13.4 availability

### ISSUE THREAD

**Issue by bfgiordano** [uniberg/kbn_sankey_vis#20]
Elastic released a security update and it looks like a move to 7.13.4 to address may be necessary. See below. Any timeline for getting Sankey plugin updated to support 7.13? My users rely on your plugin. 

https://discuss.elastic.co/t/elasticsearch-7-13-4-security-update/279177?ultron=ece-security-issue&blade=announcement&hulk=email&mkt_tok=ODEzLU1BTS0zOTIAAAF-aRbzc3TV2FTU9MSzND4v6Aas5EWezUiiX3KfXEPMOtA1ObfEBHEhLpOun2CsguKV--XoN5-73CKAc3CcgixXGMobe4oyXPRadK6vr_bXmjI97qat

**Comment by ch-bas** [comment]
Hi @bfgiordano ,
thanks for letting us know about this issue!
Unfortunately, there is no plan to update the plugin to 7.13.x in the nearest future due to the complexity of the new Kibana Plugin architecture , but we will let you know about the updates!

**Comment by bfgiordano** [comment]
Thank you - appreciate your quick response.

**Comment by ch-bas** [comment]
Closing this as we moved forward to target new versions of Kibana.
