### ISSUE TITLE
On 7.15 got a lot of errors Module NOT FOUND with ts

### ISSUE THREAD

**Issue by Requium** [uniberg/kbn_sankey_vis#22]
I installed the plugin on kibana 7.15.0 via kibana-plugins install, but checking the logs it failed to initialize kibana because the plugin cant find the config.ts (apparently it was not loaded on the zip file) i changed the file with babel so it can be export to js, and it passed but..., after i checked on server usage_collectors/getstats asks for ../../public/types, but as the config.ts file it doesnt appear on the zip file generated by the yarn plugin-build or the zip file provided on releases, i try to add it manually but babel cant transform the export lines of the ts so it will be added incomplete, i dont check it if it cause errors on kibana, i dont know if i need an special kibana with ts support? or i have to mount it on a kibana with developer tools, i just tried to get this on a docker kibana with plugin installation way to install it

**Comment by ch-bas** [comment]
Hi @Requium,
Thank you for your feedback!
Indeed this is not expected to happen.
I will try to take a look asap!

**Comment by ch-bas** [comment]
@Requium ,
I updated the pre-release to fix the issue temporarily until I will have more free time for debugging. Now you should not expect to encounter the issue anymore.
Thanks for reporting it!

**Comment by Requium** [comment]
Thanks!, it worked :) with 7.15.0, i guess we will have to wait to be corrected on the code so we can use the plugin build right? so we can use it on 7.15.1+, or could we change just the kibana.json file to be compatible to 7.15.1?

**Comment by ch-bas** [comment]
I can not guarantee that just adapting the version on the kibana.json file would be enough, most probably more work will be needed.
