### ISSUE TITLE
Sankey for 7.16 due to log4j issue

### ISSUE THREAD

**Issue by bfgiordano** [uniberg/kbn_sankey_vis#23]
Any chance of getting the Sankey plugin available for 7.16.x due to the issue with log4j and the indication from Elastic that 7.16.x is the way to go forward.

**Comment by ch-bas** [comment]
Thanks for the request, we will take it into consideration, but most likely the release will be planned for the first quarter of next year.

**Comment by ch-bas** [comment]
Hi @bfgiordano ,
a new version was uploaded today that should work with both Kibana's 7.16 and 7.17 .
Please feel free to report any issue related to the plugin as your feedback is much appreciated.
Thanks in advance!

**Comment by bfgiordano** [comment]
Thank you! So far looks good on 7.17. We are going to install on 7.16 as well but expect it will work well, too.

**Comment by ch-bas** [comment]
closed by #24 .
