### ISSUE TITLE
kibana-plugin install vs. git clone/yarn

### ISSUE THREAD

**Issue by joej** [uniberg/kbn_sankey_vis#28]
The Install section suggests git clone + yarn to "install" 
What is the proper way to install via "kibana-plugin install <filename>" -- are the zip files install-able that way?

**Comment by ch-bas** [comment]
Yes you can do so by specifying the release version that is compatible with your kibana's version.

**Comment by Neelam-zanvar** [comment]
When i run the yarn stat command i am getting the following error
yarn start
yarn run v1.22.19
$ cd ../.. && node scripts/kibana --dev --oss
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/etc/kibana/scripts/kibana'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


Using kibana version 8.7.0

**Comment by ch-bas** [comment]
Closing this issue as no further answer was given.

**Comment by Neelam-zanvar** [comment]
Ok sure. Thanks for the response
