### ISSUE TITLE
Enhancement: Way to change data view on existing Sankey

### ISSUE THREAD

**Issue by bfgiordano** [uniberg/kbn_sankey_vis#35]
Would be helpful to be able to select the data view/index from within the edit on an existing Sankey as other Kibana visuals permit.

**Comment by ch-bas** [comment]
Hi @bfgiordano ,
I agree, it will be very useful and helpful to align the plugin with Kibana's default behavior.
I will take a look on this soon.
Thank you!

**Comment by ch-bas** [comment]
Hi @bfgiordano , would you mind explaining more this issue? Because as far as I saw and tried, you can not change the data-view from the edit view on any visualisation in Kibana.
Thank you in advance!

**Comment by bfgiordano** [comment]
Not sure  I am being clear. When you create a new visualization in Kibana (Lens or Aggregation Library), you select a data view from those available in the Kibana Space that the visual uses.  When you edit the visual (again, in both Lens ad Aggregation Library), you can select a different data view (from the set available in the Kibana Space) to connect the visualization to and then save as a new visualization.
All I want is to be able to select a different data view for the visualization. Does that make sense?

**Comment by skarjoss** [comment]
This feature is also covered by PR #44

**Comment by ch-bas** [comment]
Covered by #44 .
