### ISSUE TITLE
[Enhancement request] Add a Kibana filter when clicking on data

### ISSUE THREAD

**Issue by lguillaud** [uniberg/kbn_sankey_vis#43]
Hello,

First of all, thanks for updating the plugin for the latest versions of Kibana.

Would it be feasible to add a Kibana filter when clicking on data? 
For example, when clicking on "Rome" on the left hand side, a filter is added in the Kibana filter area with OriginCityName:"Rome".

The idea is to have a similar way of working as any other build-in Kibana visualisation types (eg pie, line chart, ...) and would be very helpful when using this viz.

Currently using your plugin in Kibana 8.6.2 (derived from 8.7.0).

Thanks.
Lionel

**Comment by ch-bas** [comment]
Hi @lguillaud ,
thank you for your suggestion about the Sankey plugin.
I will try to find some time to work on your request.
Thank you!

**Comment by skarjoss** [comment]
This enhancement is covered in PR #44

**Comment by ch-bas** [comment]
Hi @lguillaud , I made a [pre-release](https://github.com/uniberg/kbn_sankey_vis/releases/tag/v.8.14.1-1) today that enhances @skarjoss PR and which should offer new features to the plugin.

Please feel free to test it!

**Comment by lguillaud** [comment]
Hello @ch-bas ,
Thanks a lot for your update but I have dowloaded the 8.6.2 release and  it seems the target directory is missing in the zip file  (I can only see kibana.json file).

**Comment by ch-bas** [comment]
Thanks for reporting the problem, I will take a look now!

Best regards!

**Comment by lguillaud** [comment]
Hello,
Got it installed from 8.6.2 release but I have an issue when clicking to apply a filter.

Context:
- Using Kibana 8.6.2
- Using dataset Kibana Sample Data Flights
- Create sankey with first split row on OriginCountry and second split row on DestCountry
- Click on first line on the left (OriginCountry) IT => IT filter is set on OriginCountry
![image](https://github.com/user-attachments/assets/dd0ca82b-9f5a-4644-9994-822d6e21ce5f)
- Remove filter and click on second line on the left (OriginCountry) US => US filter is set BUT on **DestCountry**
![image](https://github.com/user-attachments/assets/6e117262-84df-44d4-9db3-33f8148eceaf)

Thanks again for your support  ;-)

Lionel

**Comment by ch-bas** [comment]
Hi @lguillaud , the mentioned problem should be fixed now on the new release ([v2](https://github.com/uniberg/kbn_sankey_vis/releases/tag/v.8.14.1-1)), could you confirm it? 

Thanks!

**Comment by lguillaud** [comment]
Hi @ch-bas ,

Again, thanks a lot.
Just deployed and seems to be fine. 
Our team will start to use it and of course, we'll you know in case of any issue.
